apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: osok-platform
spec:
  schema:
    apiVersion: v1alpha1
    kind: OSOKPlatform
    spec:
      compartmentId: string
      availabilityDomain: string
      cidrBlock: string
      subnetCidrBlock: string
      lbSubnetId: string
      objectStorageNamespace: string
      mysqlCredentialsSecret: string
      adbAdminPasswordSecret: string
      adbDbName: string
      nosqlTableName: string
      containerImageUrl: string
      imageId: string
      # Legacy fields retained for schema compatibility; not referenced by resource templates
      subnetId: string
      vcnId: string

  resources:

    # ── 1. Vault ─────────────────────────────────────────────────────────────
    - id: vault
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciVault
        metadata:
          name: ${schema.metadata.name}-vault
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-vault
          vaultType: DEFAULT
          key:
            displayName: ${schema.metadata.name}-key
            keyShape:
              algorithm: AES
              length: 32

    # ── 2. Object Storage Bucket ──────────────────────────────────────────────
    - id: objectStorageBucket
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: ObjectStorageBucket
        metadata:
          name: ${schema.metadata.name}-bucket
        spec:
          compartmentId: ${schema.spec.compartmentId}
          name: ${schema.metadata.name}-bucket
          accessType: NoPublicAccess
          storageType: Standard
          versioning: Enabled

    # ── 3. Oracle Streaming Service ───────────────────────────────────────────
    - id: stream
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: Stream
        metadata:
          name: ${schema.metadata.name}-stream
        spec:
          compartmentId: ${schema.spec.compartmentId}
          name: ${schema.metadata.name}-stream
          partitions: 1
          retentionInHours: 24

    # ── 4. OCI Queue ──────────────────────────────────────────────────────────
    - id: queue
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciQueue
        metadata:
          name: ${schema.metadata.name}-queue
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-queue
          retentionInSeconds: 86400
          visibilityInSeconds: 30
          deadLetterQueueDeliveryCount: 3

    # ── 5. Autonomous Database ────────────────────────────────────────────────
    - id: adb
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: AutonomousDatabases
        metadata:
          name: ${schema.metadata.name}-adb
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-adb
          dbName: ${schema.spec.adbDbName}
          dbWorkload: OLTP
          computeModel: ECPU
          computeCount: 2
          dataStorageSizeInTBs: 1
          isAutoScalingEnabled: false
          isFreeTier: false
          adminPassword:
            secret:
              secretName: ${schema.spec.adbAdminPasswordSecret}

    # ── 6. VCN ────────────────────────────────────────────────────────────────
    - id: vcn
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciVcn
        metadata:
          name: ${schema.metadata.name}-vcn
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-vcn
          cidrBlock: ${schema.spec.cidrBlock}
          dnsLabel: platform

    # ── 7. Internet Gateway ───────────────────────────────────────────────────
    - id: internetGateway
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciInternetGateway
        metadata:
          name: ${schema.metadata.name}-igw
        spec:
          compartmentId: ${schema.spec.compartmentId}
          vcnId: ${vcn.status.status.ocid}
          displayName: ${schema.metadata.name}-igw
          isEnabled: true
      readyWhen:
        - ${internetGateway.status.status.ocid != ""}

    # ── 7b. NAT Gateway ────────────────────────────────────────────────────────
    - id: natGateway
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciNatGateway
        metadata:
          name: ${schema.metadata.name}-ngw
        spec:
          compartmentId: ${schema.spec.compartmentId}
          vcnId: ${vcn.status.status.ocid}
          displayName: ${schema.metadata.name}-ngw
          blockTraffic: false
      readyWhen:
        - ${natGateway.status.status.ocid != ""}

    # ── 7c. Service Gateway ───────────────────────────────────────────────────
    - id: serviceGateway
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciServiceGateway
        metadata:
          name: ${schema.metadata.name}-sgw
        spec:
          compartmentId: ${schema.spec.compartmentId}
          vcnId: ${vcn.status.status.ocid}
          displayName: ${schema.metadata.name}-sgw
          services:
            - ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna
      readyWhen:
        - ${serviceGateway.status.status.ocid != ""}

    # ── 8. Route Table ────────────────────────────────────────────────────────
    - id: routeTable
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciRouteTable
        metadata:
          name: ${schema.metadata.name}-rt
        spec:
          compartmentId: ${schema.spec.compartmentId}
          vcnId: ${vcn.status.status.ocid}
          displayName: ${schema.metadata.name}-rt
          routeRules:
            - destination: "0.0.0.0/0"
              networkEntityId: ${natGateway.status.status.ocid}
              destinationType: CIDR_BLOCK
            - destination: all-iad-services-in-oracle-services-network
              networkEntityId: ${serviceGateway.status.status.ocid}
              destinationType: SERVICE_CIDR_BLOCK
      readyWhen:
        - ${routeTable.status.status.ocid != ""}

    # ── 8b. Security List ─────────────────────────────────────────────────────
    - id: securityList
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciSecurityList
        metadata:
          name: ${schema.metadata.name}-seclist
        spec:
          compartmentId: ${schema.spec.compartmentId}
          vcnId: ${vcn.status.status.ocid}
          displayName: ${schema.metadata.name}-seclist
          egressSecurityRules:
            - protocol: "all"
              destination: all-iad-services-in-oracle-services-network
              destinationType: SERVICE_CIDR_BLOCK
              isStateless: false
              description: "Allow all egress to OCI services via SGW"
          ingressSecurityRules:
            - protocol: "6"
              source: ${schema.spec.subnetCidrBlock}
              isStateless: false
              description: "Allow TCP within subnet"
      readyWhen:
        - ${securityList.status.status.ocid != ""}

    # ── 9. Subnet ─────────────────────────────────────────────────────────────
    - id: subnet
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OciSubnet
        metadata:
          name: ${schema.metadata.name}-subnet
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-subnet
          vcnId: ${vcn.status.status.ocid}
          cidrBlock: ${schema.spec.subnetCidrBlock}
          dnsLabel: private
          prohibitPublicIpOnVnic: true
          routeTableId: ${routeTable.status.status.ocid}
          securityListIds:
            - ${securityList.status.status.ocid}

    # ── 10. MySQL DB System ───────────────────────────────────────────────────
    - id: mysql
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: MySqlDbSystem
        metadata:
          name: ${schema.metadata.name}-mysql
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-mysql
          shapeName: MySQL.VM.Standard.E3.1.8GB
          subnetId: ${subnet.status.status.ocid}
          availabilityDomain: ${schema.spec.availabilityDomain}
          mysqlVersion: "8.0.42"
          dataStorageSizeInGBs: 50
          adminUsername:
            secret:
              secretName: ${schema.spec.mysqlCredentialsSecret}
          adminPassword:
            secret:
              secretName: ${schema.spec.mysqlCredentialsSecret}

    # ── 11. PostgreSQL DB System ──────────────────────────────────────────────
    - id: postgres
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: PostgresDbSystem
        metadata:
          name: ${schema.metadata.name}-postgres
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-postgres
          dbVersion: "14"
          shape: PostgreSQL.VM.Standard.E5.Flex
          subnetId: ${subnet.status.status.ocid}
          storageType: HighPerformance
          instanceCount: 1
          instanceOcpuCount: 2
          instanceMemoryInGBs: 32
          adminUsername:
            secret:
              secretName: ${schema.spec.mysqlCredentialsSecret}
          adminPassword:
            secret:
              secretName: ${schema.spec.mysqlCredentialsSecret}

    # ── 12. NoSQL Table ───────────────────────────────────────────────────────
    - id: nosqlTable
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: NoSQLDatabase
        metadata:
          name: ${schema.metadata.name}-nosql
        spec:
          compartmentId: ${schema.spec.compartmentId}
          name: ${schema.spec.nosqlTableName}
          ddlStatement: >-
            CREATE TABLE IF NOT EXISTS ${schema.spec.nosqlTableName}
            (id STRING, ts TIMESTAMP(3), payload JSON, PRIMARY KEY(id))
          tableLimits:
            maxReadUnits: 50
            maxWriteUnits: 50
            maxStorageInGBs: 1

    # ── 13. OCI Cache with Redis ──────────────────────────────────────────────
    - id: redisCluster
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: RedisCluster
        metadata:
          name: ${schema.metadata.name}-redis
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-redis
          softwareVersion: V7_0_5
          nodeCount: 3
          nodeMemoryInGBs: 2
          subnetId: ${subnet.status.status.ocid}

    # ── 14. OpenSearch Cluster ────────────────────────────────────────────────
    - id: opensearch
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: OpenSearchCluster
        metadata:
          name: ${schema.metadata.name}-opensearch
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-opensearch
          softwareVersion: "2.11.0"
          masterNodeCount: 3
          masterNodeHostType: FLEX
          masterNodeHostOcpuCount: 2
          masterNodeHostMemoryGB: 32
          dataNodeCount: 3
          dataNodeHostType: FLEX
          dataNodeHostOcpuCount: 4
          dataNodeHostMemoryGB: 64
          dataNodeStorageGB: 100
          opendashboardNodeCount: 1
          opendashboardNodeHostOcpuCount: 2
          opendashboardNodeHostMemoryGB: 32
          vcnId: ${vcn.status.status.ocid}
          vcnCompartmentId: ${schema.spec.compartmentId}
          subnetId: ${subnet.status.status.ocid}
          subnetCompartmentId: ${schema.spec.compartmentId}

    # ── 15. API Gateway ───────────────────────────────────────────────────────
    - id: apiGateway
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: ApiGateway
        metadata:
          name: ${schema.metadata.name}-apigw
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-apigw
          endpointType: PUBLIC
          subnetId: ${schema.spec.lbSubnetId}

    # ── 16. API Gateway Deployment ────────────────────────────────────────────
    # Stock responses only — no function backend required.
    - id: apiGatewayDeployment
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: ApiGatewayDeployment
        metadata:
          name: ${schema.metadata.name}-apigw-deploy
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-apigw-deploy
          gatewayId: ${apiGateway.status.status.ocid}
          pathPrefix: /v1
          routes:
            - path: /health
              methods:
                - GET
              backend:
                type: STOCK_RESPONSE_BACKEND
                status: 200
                body: '{"status":"ok"}'

    # ── 17. Container Instance ────────────────────────────────────────────────
    - id: containerInstance
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: ContainerInstance
        metadata:
          name: ${schema.metadata.name}-ci
        spec:
          compartmentId: ${schema.spec.compartmentId}
          availabilityDomain: ${schema.spec.availabilityDomain}
          displayName: ${schema.metadata.name}-ci
          shape: CI.Standard.x86.Generic
          shapeConfig:
            ocpus: 1
            memoryInGBs: 4
          containers:
            - imageUrl: ${schema.spec.containerImageUrl}
              displayName: app
              command:
                - /bin/sh
                - -c
                - sleep infinity
              environmentVariables:
                COMPARTMENT_ID: ${schema.spec.compartmentId}
          vnics:
            - subnetId: ${subnet.status.status.ocid}
              displayName: primary-vnic
          containerRestartPolicy: ON_FAILURE

    # ── 18. Compute Instance ──────────────────────────────────────────────────
    - id: computeInstance
      template:
        apiVersion: oci.oracle.com/v1beta1
        kind: ComputeInstance
        metadata:
          name: ${schema.metadata.name}-vm
        spec:
          compartmentId: ${schema.spec.compartmentId}
          displayName: ${schema.metadata.name}-vm
          availabilityDomain: ${schema.spec.availabilityDomain}
          shape: VM.Standard.E4.Flex
          shapeConfig:
            ocpus: 1
            memoryInGBs: 16
          imageId: ${schema.spec.imageId}
          subnetId: ${subnet.status.status.ocid}
