//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGateway) DeepCopyInto(out *ApiGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGateway.
func (in *ApiGateway) DeepCopy() *ApiGateway {
	if in == nil {
		return nil
	}
	out := new(ApiGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayDeploySpec) DeepCopyInto(out *ApiGatewayDeploySpec) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]ApiGatewayRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayDeploySpec.
func (in *ApiGatewayDeploySpec) DeepCopy() *ApiGatewayDeploySpec {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayDeployStatus) DeepCopyInto(out *ApiGatewayDeployStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayDeployStatus.
func (in *ApiGatewayDeployStatus) DeepCopy() *ApiGatewayDeployStatus {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayDeployment) DeepCopyInto(out *ApiGatewayDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayDeployment.
func (in *ApiGatewayDeployment) DeepCopy() *ApiGatewayDeployment {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiGatewayDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayDeploymentList) DeepCopyInto(out *ApiGatewayDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiGatewayDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayDeploymentList.
func (in *ApiGatewayDeploymentList) DeepCopy() *ApiGatewayDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiGatewayDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayList) DeepCopyInto(out *ApiGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayList.
func (in *ApiGatewayList) DeepCopy() *ApiGatewayList {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayRoute) DeepCopyInto(out *ApiGatewayRoute) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Backend = in.Backend
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayRoute.
func (in *ApiGatewayRoute) DeepCopy() *ApiGatewayRoute {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayRouteBackend) DeepCopyInto(out *ApiGatewayRouteBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayRouteBackend.
func (in *ApiGatewayRouteBackend) DeepCopy() *ApiGatewayRouteBackend {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayRouteBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewaySpec) DeepCopyInto(out *ApiGatewaySpec) {
	*out = *in
	if in.NetworkSecurityGroupIds != nil {
		in, out := &in.NetworkSecurityGroupIds, &out.NetworkSecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewaySpec.
func (in *ApiGatewaySpec) DeepCopy() *ApiGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(ApiGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiGatewayStatus) DeepCopyInto(out *ApiGatewayStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiGatewayStatus.
func (in *ApiGatewayStatus) DeepCopy() *ApiGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(ApiGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabaseWallet) DeepCopyInto(out *AutonomousDatabaseWallet) {
	*out = *in
	out.WalletPassword = in.WalletPassword
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabaseWallet.
func (in *AutonomousDatabaseWallet) DeepCopy() *AutonomousDatabaseWallet {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabaseWallet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabases) DeepCopyInto(out *AutonomousDatabases) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabases.
func (in *AutonomousDatabases) DeepCopy() *AutonomousDatabases {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabases)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutonomousDatabases) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabasesList) DeepCopyInto(out *AutonomousDatabasesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutonomousDatabases, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabasesList.
func (in *AutonomousDatabasesList) DeepCopy() *AutonomousDatabasesList {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabasesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutonomousDatabasesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabasesSpec) DeepCopyInto(out *AutonomousDatabasesSpec) {
	*out = *in
	out.AdminPassword = in.AdminPassword
	in.TagResources.DeepCopyInto(&out.TagResources)
	out.Wallet = in.Wallet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabasesSpec.
func (in *AutonomousDatabasesSpec) DeepCopy() *AutonomousDatabasesSpec {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabasesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutonomousDatabasesStatus) DeepCopyInto(out *AutonomousDatabasesStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutonomousDatabasesStatus.
func (in *AutonomousDatabasesStatus) DeepCopy() *AutonomousDatabasesStatus {
	if in == nil {
		return nil
	}
	out := new(AutonomousDatabasesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeInstance) DeepCopyInto(out *ComputeInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeInstance.
func (in *ComputeInstance) DeepCopy() *ComputeInstance {
	if in == nil {
		return nil
	}
	out := new(ComputeInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeInstanceList) DeepCopyInto(out *ComputeInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeInstanceList.
func (in *ComputeInstanceList) DeepCopy() *ComputeInstanceList {
	if in == nil {
		return nil
	}
	out := new(ComputeInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeInstanceShapeConfig) DeepCopyInto(out *ComputeInstanceShapeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeInstanceShapeConfig.
func (in *ComputeInstanceShapeConfig) DeepCopy() *ComputeInstanceShapeConfig {
	if in == nil {
		return nil
	}
	out := new(ComputeInstanceShapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeInstanceSpec) DeepCopyInto(out *ComputeInstanceSpec) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ShapeConfig != nil {
		in, out := &in.ShapeConfig, &out.ShapeConfig
		*out = new(ComputeInstanceShapeConfig)
		**out = **in
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeInstanceSpec.
func (in *ComputeInstanceSpec) DeepCopy() *ComputeInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeInstanceStatus) DeepCopyInto(out *ComputeInstanceStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeInstanceStatus.
func (in *ComputeInstanceStatus) DeepCopy() *ComputeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerDetails) DeepCopyInto(out *ContainerDetails) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkingDirectory != nil {
		in, out := &in.WorkingDirectory, &out.WorkingDirectory
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceConfig != nil {
		in, out := &in.ResourceConfig, &out.ResourceConfig
		*out = new(ContainerResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]ContainerVolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerDetails.
func (in *ContainerDetails) DeepCopy() *ContainerDetails {
	if in == nil {
		return nil
	}
	out := new(ContainerDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImagePullSecret) DeepCopyInto(out *ContainerImagePullSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImagePullSecret.
func (in *ContainerImagePullSecret) DeepCopy() *ContainerImagePullSecret {
	if in == nil {
		return nil
	}
	out := new(ContainerImagePullSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInstance) DeepCopyInto(out *ContainerInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInstance.
func (in *ContainerInstance) DeepCopy() *ContainerInstance {
	if in == nil {
		return nil
	}
	out := new(ContainerInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInstanceGCPolicy) DeepCopyInto(out *ContainerInstanceGCPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInstanceGCPolicy.
func (in *ContainerInstanceGCPolicy) DeepCopy() *ContainerInstanceGCPolicy {
	if in == nil {
		return nil
	}
	out := new(ContainerInstanceGCPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInstanceList) DeepCopyInto(out *ContainerInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInstanceList.
func (in *ContainerInstanceList) DeepCopy() *ContainerInstanceList {
	if in == nil {
		return nil
	}
	out := new(ContainerInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInstanceShapeConfig) DeepCopyInto(out *ContainerInstanceShapeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInstanceShapeConfig.
func (in *ContainerInstanceShapeConfig) DeepCopy() *ContainerInstanceShapeConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerInstanceShapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInstanceSpec) DeepCopyInto(out *ContainerInstanceSpec) {
	*out = *in
	out.ShapeConfig = in.ShapeConfig
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Vnics != nil {
		in, out := &in.Vnics, &out.Vnics
		*out = make([]ContainerVnicDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FaultDomain != nil {
		in, out := &in.FaultDomain, &out.FaultDomain
		*out = new(string)
		**out = **in
	}
	if in.GracefulShutdownTimeoutInSeconds != nil {
		in, out := &in.GracefulShutdownTimeoutInSeconds, &out.GracefulShutdownTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ContainerRestartPolicy != nil {
		in, out := &in.ContainerRestartPolicy, &out.ContainerRestartPolicy
		*out = new(string)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ContainerImagePullSecret, len(*in))
		copy(*out, *in)
	}
	if in.GCPolicy != nil {
		in, out := &in.GCPolicy, &out.GCPolicy
		*out = new(ContainerInstanceGCPolicy)
		**out = **in
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInstanceSpec.
func (in *ContainerInstanceSpec) DeepCopy() *ContainerInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInstanceStatus) DeepCopyInto(out *ContainerInstanceStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInstanceStatus.
func (in *ContainerInstanceStatus) DeepCopy() *ContainerInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceConfig) DeepCopyInto(out *ContainerResourceConfig) {
	*out = *in
	if in.VcpusLimit != nil {
		in, out := &in.VcpusLimit, &out.VcpusLimit
		*out = new(float32)
		**out = **in
	}
	if in.MemoryLimitInGBs != nil {
		in, out := &in.MemoryLimitInGBs, &out.MemoryLimitInGBs
		*out = new(float32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceConfig.
func (in *ContainerResourceConfig) DeepCopy() *ContainerResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerVnicDetails) DeepCopyInto(out *ContainerVnicDetails) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]OCID, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerVnicDetails.
func (in *ContainerVnicDetails) DeepCopy() *ContainerVnicDetails {
	if in == nil {
		return nil
	}
	out := new(ContainerVnicDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerVolumeMount) DeepCopyInto(out *ContainerVolumeMount) {
	*out = *in
	if in.SubPath != nil {
		in, out := &in.SubPath, &out.SubPath
		*out = new(string)
		**out = **in
	}
	if in.IsReadOnly != nil {
		in, out := &in.IsReadOnly, &out.IsReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerVolumeMount.
func (in *ContainerVolumeMount) DeepCopy() *ContainerVolumeMount {
	if in == nil {
		return nil
	}
	out := new(ContainerVolumeMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateBackupPolicyDetails) DeepCopyInto(out *CreateBackupPolicyDetails) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateBackupPolicyDetails.
func (in *CreateBackupPolicyDetails) DeepCopy() *CreateBackupPolicyDetails {
	if in == nil {
		return nil
	}
	out := new(CreateBackupPolicyDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateConfigurationDetails) DeepCopyInto(out *CreateConfigurationDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateConfigurationDetails.
func (in *CreateConfigurationDetails) DeepCopy() *CreateConfigurationDetails {
	if in == nil {
		return nil
	}
	out := new(CreateConfigurationDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateDbSystemSourceDetails) DeepCopyInto(out *CreateDbSystemSourceDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateDbSystemSourceDetails.
func (in *CreateDbSystemSourceDetails) DeepCopy() *CreateDbSystemSourceDetails {
	if in == nil {
		return nil
	}
	out := new(CreateDbSystemSourceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateMaintenanceDetails) DeepCopyInto(out *CreateMaintenanceDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateMaintenanceDetails.
func (in *CreateMaintenanceDetails) DeepCopy() *CreateMaintenanceDetails {
	if in == nil {
		return nil
	}
	out := new(CreateMaintenanceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowApplication) DeepCopyInto(out *DataFlowApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowApplication.
func (in *DataFlowApplication) DeepCopy() *DataFlowApplication {
	if in == nil {
		return nil
	}
	out := new(DataFlowApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlowApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowApplicationList) DeepCopyInto(out *DataFlowApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataFlowApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowApplicationList.
func (in *DataFlowApplicationList) DeepCopy() *DataFlowApplicationList {
	if in == nil {
		return nil
	}
	out := new(DataFlowApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlowApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowApplicationSpec) DeepCopyInto(out *DataFlowApplicationSpec) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowApplicationSpec.
func (in *DataFlowApplicationSpec) DeepCopy() *DataFlowApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(DataFlowApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowApplicationStatus) DeepCopyInto(out *DataFlowApplicationStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowApplicationStatus.
func (in *DataFlowApplicationStatus) DeepCopy() *DataFlowApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(DataFlowApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressSecurityRule) DeepCopyInto(out *EgressSecurityRule) {
	*out = *in
	if in.TcpOptions != nil {
		in, out := &in.TcpOptions, &out.TcpOptions
		*out = new(TcpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.UdpOptions != nil {
		in, out := &in.UdpOptions, &out.UdpOptions
		*out = new(UdpOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressSecurityRule.
func (in *EgressSecurityRule) DeepCopy() *EgressSecurityRule {
	if in == nil {
		return nil
	}
	out := new(EgressSecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsApplication) DeepCopyInto(out *FunctionsApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsApplication.
func (in *FunctionsApplication) DeepCopy() *FunctionsApplication {
	if in == nil {
		return nil
	}
	out := new(FunctionsApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionsApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsApplicationList) DeepCopyInto(out *FunctionsApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionsApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsApplicationList.
func (in *FunctionsApplicationList) DeepCopy() *FunctionsApplicationList {
	if in == nil {
		return nil
	}
	out := new(FunctionsApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionsApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsApplicationSpec) DeepCopyInto(out *FunctionsApplicationSpec) {
	*out = *in
	if in.SubnetIds != nil {
		in, out := &in.SubnetIds, &out.SubnetIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NetworkSecurityGroupIds != nil {
		in, out := &in.NetworkSecurityGroupIds, &out.NetworkSecurityGroupIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsApplicationSpec.
func (in *FunctionsApplicationSpec) DeepCopy() *FunctionsApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionsApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsApplicationStatus) DeepCopyInto(out *FunctionsApplicationStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsApplicationStatus.
func (in *FunctionsApplicationStatus) DeepCopy() *FunctionsApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionsApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsFunction) DeepCopyInto(out *FunctionsFunction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsFunction.
func (in *FunctionsFunction) DeepCopy() *FunctionsFunction {
	if in == nil {
		return nil
	}
	out := new(FunctionsFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionsFunction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsFunctionList) DeepCopyInto(out *FunctionsFunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionsFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsFunctionList.
func (in *FunctionsFunctionList) DeepCopy() *FunctionsFunctionList {
	if in == nil {
		return nil
	}
	out := new(FunctionsFunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionsFunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsFunctionSpec) DeepCopyInto(out *FunctionsFunctionSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsFunctionSpec.
func (in *FunctionsFunctionSpec) DeepCopy() *FunctionsFunctionSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionsFunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsFunctionStatus) DeepCopyInto(out *FunctionsFunctionStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsFunctionStatus.
func (in *FunctionsFunctionStatus) DeepCopy() *FunctionsFunctionStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionsFunctionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSecurityRule) DeepCopyInto(out *IngressSecurityRule) {
	*out = *in
	if in.TcpOptions != nil {
		in, out := &in.TcpOptions, &out.TcpOptions
		*out = new(TcpOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.UdpOptions != nil {
		in, out := &in.UdpOptions, &out.UdpOptions
		*out = new(UdpOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSecurityRule.
func (in *IngressSecurityRule) DeepCopy() *IngressSecurityRule {
	if in == nil {
		return nil
	}
	out := new(IngressSecurityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MapValue) DeepCopyInto(out *MapValue) {
	{
		in := &in
		*out = make(MapValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapValue.
func (in MapValue) DeepCopy() MapValue {
	if in == nil {
		return nil
	}
	out := new(MapValue)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySqlDbSystem) DeepCopyInto(out *MySqlDbSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySqlDbSystem.
func (in *MySqlDbSystem) DeepCopy() *MySqlDbSystem {
	if in == nil {
		return nil
	}
	out := new(MySqlDbSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MySqlDbSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySqlDbSystemList) DeepCopyInto(out *MySqlDbSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MySqlDbSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySqlDbSystemList.
func (in *MySqlDbSystemList) DeepCopy() *MySqlDbSystemList {
	if in == nil {
		return nil
	}
	out := new(MySqlDbSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MySqlDbSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySqlDbSystemSpec) DeepCopyInto(out *MySqlDbSystemSpec) {
	*out = *in
	out.AdminUsername = in.AdminUsername
	out.AdminPassword = in.AdminPassword
	out.ConfigurationId = in.ConfigurationId
	in.BackupPolicy.DeepCopyInto(&out.BackupPolicy)
	out.Source = in.Source
	out.Maintenance = in.Maintenance
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySqlDbSystemSpec.
func (in *MySqlDbSystemSpec) DeepCopy() *MySqlDbSystemSpec {
	if in == nil {
		return nil
	}
	out := new(MySqlDbSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySqlDbSystemStatus) DeepCopyInto(out *MySqlDbSystemStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySqlDbSystemStatus.
func (in *MySqlDbSystemStatus) DeepCopy() *MySqlDbSystemStatus {
	if in == nil {
		return nil
	}
	out := new(MySqlDbSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoSQLDatabase) DeepCopyInto(out *NoSQLDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoSQLDatabase.
func (in *NoSQLDatabase) DeepCopy() *NoSQLDatabase {
	if in == nil {
		return nil
	}
	out := new(NoSQLDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NoSQLDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoSQLDatabaseList) DeepCopyInto(out *NoSQLDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NoSQLDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoSQLDatabaseList.
func (in *NoSQLDatabaseList) DeepCopy() *NoSQLDatabaseList {
	if in == nil {
		return nil
	}
	out := new(NoSQLDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NoSQLDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoSQLDatabaseSpec) DeepCopyInto(out *NoSQLDatabaseSpec) {
	*out = *in
	if in.TableLimits != nil {
		in, out := &in.TableLimits, &out.TableLimits
		*out = new(NoSQLDatabaseTableLimits)
		**out = **in
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoSQLDatabaseSpec.
func (in *NoSQLDatabaseSpec) DeepCopy() *NoSQLDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(NoSQLDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoSQLDatabaseStatus) DeepCopyInto(out *NoSQLDatabaseStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoSQLDatabaseStatus.
func (in *NoSQLDatabaseStatus) DeepCopy() *NoSQLDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(NoSQLDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NoSQLDatabaseTableLimits) DeepCopyInto(out *NoSQLDatabaseTableLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NoSQLDatabaseTableLimits.
func (in *NoSQLDatabaseTableLimits) DeepCopy() *NoSQLDatabaseTableLimits {
	if in == nil {
		return nil
	}
	out := new(NoSQLDatabaseTableLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSOKCondition) DeepCopyInto(out *OSOKCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSOKCondition.
func (in *OSOKCondition) DeepCopy() *OSOKCondition {
	if in == nil {
		return nil
	}
	out := new(OSOKCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSOKStatus) DeepCopyInto(out *OSOKStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]OSOKCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.RequestedAt != nil {
		in, out := &in.RequestedAt, &out.RequestedAt
		*out = (*in).DeepCopy()
	}
	if in.DeletedAt != nil {
		in, out := &in.DeletedAt, &out.DeletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSOKStatus.
func (in *OSOKStatus) DeepCopy() *OSOKStatus {
	if in == nil {
		return nil
	}
	out := new(OSOKStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageBucket) DeepCopyInto(out *ObjectStorageBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageBucket.
func (in *ObjectStorageBucket) DeepCopy() *ObjectStorageBucket {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectStorageBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageBucketList) DeepCopyInto(out *ObjectStorageBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectStorageBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageBucketList.
func (in *ObjectStorageBucketList) DeepCopy() *ObjectStorageBucketList {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectStorageBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageBucketSpec) DeepCopyInto(out *ObjectStorageBucketSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageBucketSpec.
func (in *ObjectStorageBucketSpec) DeepCopy() *ObjectStorageBucketSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageBucketStatus) DeepCopyInto(out *ObjectStorageBucketStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageBucketStatus.
func (in *ObjectStorageBucketStatus) DeepCopy() *ObjectStorageBucketStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciDrg) DeepCopyInto(out *OciDrg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciDrg.
func (in *OciDrg) DeepCopy() *OciDrg {
	if in == nil {
		return nil
	}
	out := new(OciDrg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciDrg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciDrgList) DeepCopyInto(out *OciDrgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciDrg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciDrgList.
func (in *OciDrgList) DeepCopy() *OciDrgList {
	if in == nil {
		return nil
	}
	out := new(OciDrgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciDrgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciDrgSpec) DeepCopyInto(out *OciDrgSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciDrgSpec.
func (in *OciDrgSpec) DeepCopy() *OciDrgSpec {
	if in == nil {
		return nil
	}
	out := new(OciDrgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciDrgStatus) DeepCopyInto(out *OciDrgStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciDrgStatus.
func (in *OciDrgStatus) DeepCopy() *OciDrgStatus {
	if in == nil {
		return nil
	}
	out := new(OciDrgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciInternetGateway) DeepCopyInto(out *OciInternetGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciInternetGateway.
func (in *OciInternetGateway) DeepCopy() *OciInternetGateway {
	if in == nil {
		return nil
	}
	out := new(OciInternetGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciInternetGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciInternetGatewayList) DeepCopyInto(out *OciInternetGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciInternetGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciInternetGatewayList.
func (in *OciInternetGatewayList) DeepCopy() *OciInternetGatewayList {
	if in == nil {
		return nil
	}
	out := new(OciInternetGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciInternetGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciInternetGatewaySpec) DeepCopyInto(out *OciInternetGatewaySpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciInternetGatewaySpec.
func (in *OciInternetGatewaySpec) DeepCopy() *OciInternetGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(OciInternetGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciInternetGatewayStatus) DeepCopyInto(out *OciInternetGatewayStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciInternetGatewayStatus.
func (in *OciInternetGatewayStatus) DeepCopy() *OciInternetGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(OciInternetGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNatGateway) DeepCopyInto(out *OciNatGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNatGateway.
func (in *OciNatGateway) DeepCopy() *OciNatGateway {
	if in == nil {
		return nil
	}
	out := new(OciNatGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciNatGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNatGatewayList) DeepCopyInto(out *OciNatGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciNatGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNatGatewayList.
func (in *OciNatGatewayList) DeepCopy() *OciNatGatewayList {
	if in == nil {
		return nil
	}
	out := new(OciNatGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciNatGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNatGatewaySpec) DeepCopyInto(out *OciNatGatewaySpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNatGatewaySpec.
func (in *OciNatGatewaySpec) DeepCopy() *OciNatGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(OciNatGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNatGatewayStatus) DeepCopyInto(out *OciNatGatewayStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNatGatewayStatus.
func (in *OciNatGatewayStatus) DeepCopy() *OciNatGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(OciNatGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNetworkSecurityGroup) DeepCopyInto(out *OciNetworkSecurityGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNetworkSecurityGroup.
func (in *OciNetworkSecurityGroup) DeepCopy() *OciNetworkSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(OciNetworkSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciNetworkSecurityGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNetworkSecurityGroupList) DeepCopyInto(out *OciNetworkSecurityGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciNetworkSecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNetworkSecurityGroupList.
func (in *OciNetworkSecurityGroupList) DeepCopy() *OciNetworkSecurityGroupList {
	if in == nil {
		return nil
	}
	out := new(OciNetworkSecurityGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciNetworkSecurityGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNetworkSecurityGroupSpec) DeepCopyInto(out *OciNetworkSecurityGroupSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNetworkSecurityGroupSpec.
func (in *OciNetworkSecurityGroupSpec) DeepCopy() *OciNetworkSecurityGroupSpec {
	if in == nil {
		return nil
	}
	out := new(OciNetworkSecurityGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciNetworkSecurityGroupStatus) DeepCopyInto(out *OciNetworkSecurityGroupStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciNetworkSecurityGroupStatus.
func (in *OciNetworkSecurityGroupStatus) DeepCopy() *OciNetworkSecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(OciNetworkSecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciQueue) DeepCopyInto(out *OciQueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciQueue.
func (in *OciQueue) DeepCopy() *OciQueue {
	if in == nil {
		return nil
	}
	out := new(OciQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciQueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciQueueList) DeepCopyInto(out *OciQueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciQueue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciQueueList.
func (in *OciQueueList) DeepCopy() *OciQueueList {
	if in == nil {
		return nil
	}
	out := new(OciQueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciQueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciQueueSpec) DeepCopyInto(out *OciQueueSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciQueueSpec.
func (in *OciQueueSpec) DeepCopy() *OciQueueSpec {
	if in == nil {
		return nil
	}
	out := new(OciQueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciQueueStatus) DeepCopyInto(out *OciQueueStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciQueueStatus.
func (in *OciQueueStatus) DeepCopy() *OciQueueStatus {
	if in == nil {
		return nil
	}
	out := new(OciQueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciRouteTable) DeepCopyInto(out *OciRouteTable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciRouteTable.
func (in *OciRouteTable) DeepCopy() *OciRouteTable {
	if in == nil {
		return nil
	}
	out := new(OciRouteTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciRouteTable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciRouteTableList) DeepCopyInto(out *OciRouteTableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciRouteTable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciRouteTableList.
func (in *OciRouteTableList) DeepCopy() *OciRouteTableList {
	if in == nil {
		return nil
	}
	out := new(OciRouteTableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciRouteTableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciRouteTableSpec) DeepCopyInto(out *OciRouteTableSpec) {
	*out = *in
	if in.RouteRules != nil {
		in, out := &in.RouteRules, &out.RouteRules
		*out = make([]RouteRule, len(*in))
		copy(*out, *in)
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciRouteTableSpec.
func (in *OciRouteTableSpec) DeepCopy() *OciRouteTableSpec {
	if in == nil {
		return nil
	}
	out := new(OciRouteTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciRouteTableStatus) DeepCopyInto(out *OciRouteTableStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciRouteTableStatus.
func (in *OciRouteTableStatus) DeepCopy() *OciRouteTableStatus {
	if in == nil {
		return nil
	}
	out := new(OciRouteTableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSecurityList) DeepCopyInto(out *OciSecurityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSecurityList.
func (in *OciSecurityList) DeepCopy() *OciSecurityList {
	if in == nil {
		return nil
	}
	out := new(OciSecurityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciSecurityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSecurityListList) DeepCopyInto(out *OciSecurityListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciSecurityList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSecurityListList.
func (in *OciSecurityListList) DeepCopy() *OciSecurityListList {
	if in == nil {
		return nil
	}
	out := new(OciSecurityListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciSecurityListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSecurityListSpec) DeepCopyInto(out *OciSecurityListSpec) {
	*out = *in
	if in.IngressSecurityRules != nil {
		in, out := &in.IngressSecurityRules, &out.IngressSecurityRules
		*out = make([]IngressSecurityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EgressSecurityRules != nil {
		in, out := &in.EgressSecurityRules, &out.EgressSecurityRules
		*out = make([]EgressSecurityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSecurityListSpec.
func (in *OciSecurityListSpec) DeepCopy() *OciSecurityListSpec {
	if in == nil {
		return nil
	}
	out := new(OciSecurityListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSecurityListStatus) DeepCopyInto(out *OciSecurityListStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSecurityListStatus.
func (in *OciSecurityListStatus) DeepCopy() *OciSecurityListStatus {
	if in == nil {
		return nil
	}
	out := new(OciSecurityListStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciServiceGateway) DeepCopyInto(out *OciServiceGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciServiceGateway.
func (in *OciServiceGateway) DeepCopy() *OciServiceGateway {
	if in == nil {
		return nil
	}
	out := new(OciServiceGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciServiceGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciServiceGatewayList) DeepCopyInto(out *OciServiceGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciServiceGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciServiceGatewayList.
func (in *OciServiceGatewayList) DeepCopy() *OciServiceGatewayList {
	if in == nil {
		return nil
	}
	out := new(OciServiceGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciServiceGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciServiceGatewaySpec) DeepCopyInto(out *OciServiceGatewaySpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciServiceGatewaySpec.
func (in *OciServiceGatewaySpec) DeepCopy() *OciServiceGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(OciServiceGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciServiceGatewayStatus) DeepCopyInto(out *OciServiceGatewayStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciServiceGatewayStatus.
func (in *OciServiceGatewayStatus) DeepCopy() *OciServiceGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(OciServiceGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSubnet) DeepCopyInto(out *OciSubnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSubnet.
func (in *OciSubnet) DeepCopy() *OciSubnet {
	if in == nil {
		return nil
	}
	out := new(OciSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciSubnet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSubnetList) DeepCopyInto(out *OciSubnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSubnetList.
func (in *OciSubnetList) DeepCopy() *OciSubnetList {
	if in == nil {
		return nil
	}
	out := new(OciSubnetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciSubnetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSubnetSpec) DeepCopyInto(out *OciSubnetSpec) {
	*out = *in
	if in.SecurityListIds != nil {
		in, out := &in.SecurityListIds, &out.SecurityListIds
		*out = make([]OCID, len(*in))
		copy(*out, *in)
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSubnetSpec.
func (in *OciSubnetSpec) DeepCopy() *OciSubnetSpec {
	if in == nil {
		return nil
	}
	out := new(OciSubnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciSubnetStatus) DeepCopyInto(out *OciSubnetStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciSubnetStatus.
func (in *OciSubnetStatus) DeepCopy() *OciSubnetStatus {
	if in == nil {
		return nil
	}
	out := new(OciSubnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVault) DeepCopyInto(out *OciVault) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVault.
func (in *OciVault) DeepCopy() *OciVault {
	if in == nil {
		return nil
	}
	out := new(OciVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciVault) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVaultKeyShape) DeepCopyInto(out *OciVaultKeyShape) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVaultKeyShape.
func (in *OciVaultKeyShape) DeepCopy() *OciVaultKeyShape {
	if in == nil {
		return nil
	}
	out := new(OciVaultKeyShape)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVaultKeySpec) DeepCopyInto(out *OciVaultKeySpec) {
	*out = *in
	out.KeyShape = in.KeyShape
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVaultKeySpec.
func (in *OciVaultKeySpec) DeepCopy() *OciVaultKeySpec {
	if in == nil {
		return nil
	}
	out := new(OciVaultKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVaultList) DeepCopyInto(out *OciVaultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciVault, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVaultList.
func (in *OciVaultList) DeepCopy() *OciVaultList {
	if in == nil {
		return nil
	}
	out := new(OciVaultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciVaultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVaultSpec) DeepCopyInto(out *OciVaultSpec) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(OciVaultKeySpec)
		**out = **in
	}
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVaultSpec.
func (in *OciVaultSpec) DeepCopy() *OciVaultSpec {
	if in == nil {
		return nil
	}
	out := new(OciVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVaultStatus) DeepCopyInto(out *OciVaultStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVaultStatus.
func (in *OciVaultStatus) DeepCopy() *OciVaultStatus {
	if in == nil {
		return nil
	}
	out := new(OciVaultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVcn) DeepCopyInto(out *OciVcn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVcn.
func (in *OciVcn) DeepCopy() *OciVcn {
	if in == nil {
		return nil
	}
	out := new(OciVcn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciVcn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVcnList) DeepCopyInto(out *OciVcnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OciVcn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVcnList.
func (in *OciVcnList) DeepCopy() *OciVcnList {
	if in == nil {
		return nil
	}
	out := new(OciVcnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OciVcnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVcnSpec) DeepCopyInto(out *OciVcnSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVcnSpec.
func (in *OciVcnSpec) DeepCopy() *OciVcnSpec {
	if in == nil {
		return nil
	}
	out := new(OciVcnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciVcnStatus) DeepCopyInto(out *OciVcnStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciVcnStatus.
func (in *OciVcnStatus) DeepCopy() *OciVcnStatus {
	if in == nil {
		return nil
	}
	out := new(OciVcnStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchCluster) DeepCopyInto(out *OpenSearchCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchCluster.
func (in *OpenSearchCluster) DeepCopy() *OpenSearchCluster {
	if in == nil {
		return nil
	}
	out := new(OpenSearchCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenSearchCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchClusterList) DeepCopyInto(out *OpenSearchClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenSearchCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchClusterList.
func (in *OpenSearchClusterList) DeepCopy() *OpenSearchClusterList {
	if in == nil {
		return nil
	}
	out := new(OpenSearchClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenSearchClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchClusterSpec) DeepCopyInto(out *OpenSearchClusterSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchClusterSpec.
func (in *OpenSearchClusterSpec) DeepCopy() *OpenSearchClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OpenSearchClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchClusterStatus) DeepCopyInto(out *OpenSearchClusterStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchClusterStatus.
func (in *OpenSearchClusterStatus) DeepCopy() *OpenSearchClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OpenSearchClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSource) DeepCopyInto(out *PasswordSource) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSource.
func (in *PasswordSource) DeepCopy() *PasswordSource {
	if in == nil {
		return nil
	}
	out := new(PasswordSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortRange) DeepCopyInto(out *PortRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortRange.
func (in *PortRange) DeepCopy() *PortRange {
	if in == nil {
		return nil
	}
	out := new(PortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDbSystem) DeepCopyInto(out *PostgresDbSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDbSystem.
func (in *PostgresDbSystem) DeepCopy() *PostgresDbSystem {
	if in == nil {
		return nil
	}
	out := new(PostgresDbSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresDbSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDbSystemList) DeepCopyInto(out *PostgresDbSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresDbSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDbSystemList.
func (in *PostgresDbSystemList) DeepCopy() *PostgresDbSystemList {
	if in == nil {
		return nil
	}
	out := new(PostgresDbSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresDbSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDbSystemSpec) DeepCopyInto(out *PostgresDbSystemSpec) {
	*out = *in
	out.AdminUsername = in.AdminUsername
	out.AdminPassword = in.AdminPassword
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDbSystemSpec.
func (in *PostgresDbSystemSpec) DeepCopy() *PostgresDbSystemSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresDbSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDbSystemStatus) DeepCopyInto(out *PostgresDbSystemStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDbSystemStatus.
func (in *PostgresDbSystemStatus) DeepCopy() *PostgresDbSystemStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresDbSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisCluster) DeepCopyInto(out *RedisCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisCluster.
func (in *RedisCluster) DeepCopy() *RedisCluster {
	if in == nil {
		return nil
	}
	out := new(RedisCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisClusterList) DeepCopyInto(out *RedisClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RedisCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisClusterList.
func (in *RedisClusterList) DeepCopy() *RedisClusterList {
	if in == nil {
		return nil
	}
	out := new(RedisClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisClusterSpec) DeepCopyInto(out *RedisClusterSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisClusterSpec.
func (in *RedisClusterSpec) DeepCopy() *RedisClusterSpec {
	if in == nil {
		return nil
	}
	out := new(RedisClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisClusterStatus) DeepCopyInto(out *RedisClusterStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisClusterStatus.
func (in *RedisClusterStatus) DeepCopy() *RedisClusterStatus {
	if in == nil {
		return nil
	}
	out := new(RedisClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteRule) DeepCopyInto(out *RouteRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteRule.
func (in *RouteRule) DeepCopy() *RouteRule {
	if in == nil {
		return nil
	}
	out := new(RouteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSource) DeepCopyInto(out *SecretSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSource.
func (in *SecretSource) DeepCopy() *SecretSource {
	if in == nil {
		return nil
	}
	out := new(SecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stream) DeepCopyInto(out *Stream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stream.
func (in *Stream) DeepCopy() *Stream {
	if in == nil {
		return nil
	}
	out := new(Stream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Stream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamList) DeepCopyInto(out *StreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Stream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamList.
func (in *StreamList) DeepCopy() *StreamList {
	if in == nil {
		return nil
	}
	out := new(StreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamSpec) DeepCopyInto(out *StreamSpec) {
	*out = *in
	in.TagResources.DeepCopyInto(&out.TagResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamSpec.
func (in *StreamSpec) DeepCopy() *StreamSpec {
	if in == nil {
		return nil
	}
	out := new(StreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamStatus) DeepCopyInto(out *StreamStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamStatus.
func (in *StreamStatus) DeepCopy() *StreamStatus {
	if in == nil {
		return nil
	}
	out := new(StreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagResources) DeepCopyInto(out *TagResources) {
	*out = *in
	if in.FreeFormTags != nil {
		in, out := &in.FreeFormTags, &out.FreeFormTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagResources.
func (in *TagResources) DeepCopy() *TagResources {
	if in == nil {
		return nil
	}
	out := new(TagResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcpOptions) DeepCopyInto(out *TcpOptions) {
	*out = *in
	if in.DestinationPortRange != nil {
		in, out := &in.DestinationPortRange, &out.DestinationPortRange
		*out = new(PortRange)
		**out = **in
	}
	if in.SourcePortRange != nil {
		in, out := &in.SourcePortRange, &out.SourcePortRange
		*out = new(PortRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcpOptions.
func (in *TcpOptions) DeepCopy() *TcpOptions {
	if in == nil {
		return nil
	}
	out := new(TcpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdpOptions) DeepCopyInto(out *UdpOptions) {
	*out = *in
	if in.DestinationPortRange != nil {
		in, out := &in.DestinationPortRange, &out.DestinationPortRange
		*out = new(PortRange)
		**out = **in
	}
	if in.SourcePortRange != nil {
		in, out := &in.SourcePortRange, &out.SourcePortRange
		*out = new(PortRange)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdpOptions.
func (in *UdpOptions) DeepCopy() *UdpOptions {
	if in == nil {
		return nil
	}
	out := new(UdpOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsernameSource) DeepCopyInto(out *UsernameSource) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsernameSource.
func (in *UsernameSource) DeepCopy() *UsernameSource {
	if in == nil {
		return nil
	}
	out := new(UsernameSource)
	in.DeepCopyInto(out)
	return out
}
