#
# Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

resources:
- bases/oci.oracle.com_autonomousdatabases.yaml
- bases/oci.oracle.com_streams.yaml
- bases/oci.oracle.com_mysqldbsystems.yaml
- bases/oci.oracle.com_opensearchclusters.yaml
- bases/oci.oracle.com_apigateways.yaml
- bases/oci.oracle.com_apigatewaydeployments.yaml
- bases/oci.oracle.com_containerinstances.yaml
- bases/oci.oracle.com_dataflowapplications.yaml
- bases/oci.oracle.com_functionsapplications.yaml
- bases/oci.oracle.com_functionsfunctions.yaml
- bases/oci.oracle.com_nosqldatabases.yaml
- bases/oci.oracle.com_objectstoragebuckets.yaml
- bases/oci.oracle.com_ociqueues.yaml
- bases/oci.oracle.com_postgresdbsystems.yaml
- bases/oci.oracle.com_redisclusters.yaml
- bases/oci.oracle.com_ocivcns.yaml
- bases/oci.oracle.com_ocisubnets.yaml
- bases/oci.oracle.com_ociinternetgateways.yaml
- bases/oci.oracle.com_ocinatgateways.yaml
- bases/oci.oracle.com_ociservicegateways.yaml
- bases/oci.oracle.com_ocidrgs.yaml
- bases/oci.oracle.com_ocisecuritylists.yaml
- bases/oci.oracle.com_ocinetworksecuritygroups.yaml
- bases/oci.oracle.com_ociroutetables.yaml
# +kubebuilder:scaffold:crdkustomizeresource
